# Generated by Django 4.1.3 on 2022-12-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='name',
            new_name='title',
        ),
    ]
